databases:
  - name: purple_archive_db
    databaseName: purple_archive_db
    user: purple_archive_db
    region: singapore
    plan: free

services:
  # A Docker web service
  - type: web
    name: purple_archive_server
    runtime: python
    region: singapore
    plan: free
    buildCommand: "./build.sh"
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.10
      - key: POETRY_VERSION
        value: 1.5.1
      - key: DATABASE_URL
        fromDatabase:
          name: purple_archive_db
          property: connectionString
