databases:
  - name: purple_archive_db
    databaseName: purple_archive_db
    user: purple_archive_db

services:
  - type: web
    name: purple_archive_server
    runtime: python
    region: singapore
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn purple_archive_server.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.10
      - key: POETRY_VERSION
        value: 1.5.1
      - key: DATABASE_URL
        fromDatabase:
          name: purple_archive_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
