"""Add thumb_source to album

Revision ID: cf68beedb410
Revises: ea68b8b754f2
Create Date: 2023-10-05 00:35:54.240924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf68beedb410'
down_revision: Union[str, None] = 'ea68b8b754f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('thumb_source', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'thumb_source')
    # ### end Alembic commands ###
