"""Save hash to temp_album

Revision ID: ea68b8b754f2
Revises: 6922a7d0a04f
Create Date: 2023-10-04 01:22:43.251974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea68b8b754f2'
down_revision: Union[str, None] = '6922a7d0a04f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_album', sa.Column('hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_album', 'hash')
    # ### end Alembic commands ###
