# Generated by Django 4.2.3 on 2023-07-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
